version: '3.8'

services:
  web:
    restart: always
    build: ./
    command: >
      sh -c "python manage.py collectstatic --clear --noinput &&
             python manage.py migrate &&
             gunicorn -b 0.0.0.0:8000 marketplace.asgi:application -k uvicorn.workers.UvicornWorker"
    ports:
      - 8000:8000
    environment:
      - DEBUG=0
      - SECRET_KEY=foo
      - DJANGO_ALLOWED_HOSTS=localhost;127.0.0.1;[::1]
      - SIMPLE_SETTINGS=marketplace.settings.production
      - DJANGO_SETTINGS_MODULE=marketplace.settings.production
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/postgres
      - DATABASE_DEFAULT_SSL_REQUIRE=0
      - REDIS_URL=redis://redis:6379/1
    volumes:
      - ./:/usr/src/app/
    depends_on:
      - postgres
      - redis
    networks:
      - marketplace_network
  postgres:
    restart: always
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - marketplace_network
  redis:
    restart: always
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    networks:
      - marketplace_network

volumes:
  postgres_data:
  redis_data:

networks:
  marketplace_network:
    driver: bridge
