version: '3.8'

services:
  postgres:
    restart: on-failure
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - marketplace_network
  redis:
    restart: on-failure
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    networks:
      - marketplace_network

volumes:
  postgres_data:
  redis_data:

networks:
  marketplace_network:
    driver: bridge
