# Generated by Django 3.2 on 2021-04-13 19:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('product_id', models.UUIDField(help_text='\n        The product ID entered will be consultd in an external API to confirm\n        that it exists. You can see the products available at\n        https://challenge-api.luizalabs.com/api/product/?page=1\n        ', verbose_name='Product Id')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='favorite_client', to='clients.client', verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Favorite',
                'verbose_name_plural': 'Favorites',
                'ordering': ['-created_at'],
                'unique_together': {('product_id', 'client')},
            },
        ),
    ]
